server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ddeuda
    password: Emek33##
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    showSql: true
    hibernate:
      ddl-auto: update
security:
  oauth2:
    jwt:
      signkey: 123@#$